### ISSUE TITLE
Encode

### ISSUE THREAD

**Issue by hitsthings** [devongovett/png.js#10]
Thanks a ton for png.js! I'm loving it for handling ARDrone video.

It would be awesome if it were bidirectional as well - `PNG.encode(rgbaData, width, height);` and `png.save('filename.png');` I want to send a stream of PNGs up to the browser after piping them through some processing.

I can try to implement this, but I'm a bit intimidated by http://www.w3.org/TR/PNG/ . Any help you (or anyone reading this) can give would be much appreciated.

**Comment by MichalPaszkiewicz** [comment]
Bump. This is a limiting factor on the node module.

**Comment by devongovett** [comment]
You should use [png-stream](http://github.com/devongovett/png-stream). It's better for both encoding and decoding.

**Comment by MichalPaszkiewicz** [comment]
Cool! Thanks
